### ISSUE TITLE
Trouble with higher num: values

### ISSUE THREAD

**Issue by AirborneEagle** [simibac/ConfettiSwiftUI#17]
### Expected Behaviour
There should appear the number of confetti I decide

### Actual Behavior
it takes too long to render the number I have chosen. and either they do not render, or they are delayed, and then disappear suddenly during animation.

### Steps to Reproduce the Issue
- Create a confetti cannon with a higher `num:`
I would like up to 1000. but I was having issues even with 100-200 or more.

**Comment by simibac** [comment]
Thanks for reporting. What device are you using?

**Comment by simibac** [comment]
This project is an experiment to learn how to animate and span new views in SwiftUI. It is not the most perfomant way of animating large numbers of views, I agree. Especially old devices will have a hard time. Have a look at CAEmitterLayer for better performance.
