### ISSUE TITLE
Crash when app goes to background before animation is complete

### ISSUE THREAD

**Issue by twestley** [simibac/ConfettiSwiftUI#22]
### Expected Behaviour
Animation stops when app goes to background or completes successfully while in background

### Actual Behaviour
"Fatal error: Index out of range," on line 134, "animate[value-1].toggle()"
value in this statement is 0 leading to "index out of range"

### Steps to Reproduce the Issue
- Do something that triggers confetti animation
- Press Home button before animation is complete
- Reproduce

![Screen Shot 2022-04-22 at 12 52 44 PM](https://user-images.githubusercontent.com/1317260/164759720-aca8c954-0de9-4c60-8d40-150ff1a72e5a.png)

**Comment by simibac** [comment]
Thanks for the PR. Should be fixed now in the latest release.
