### ISSUE TITLE
SF Symbols support

### ISSUE THREAD

**Issue by daver234** [simibac/ConfettiSwiftUI#26]
### Description

Is there a way to use SF Symbols in ConfettiSwiftUI?  I tried embedding in Text but that did not work.  Thanks.

### Tasks

- [ ] ...

### Context 
_...mention related issues and/or user stories..._

**Comment by simibac** [comment]
Yes this was merged recently. Check related PR: https://github.com/simibac/ConfettiSwiftUI/pull/14

**Comment by daver234** [comment]
Excellent.  Works.  Thanks!
