### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by chrisjf** [simibac/ConfettiSwiftUI#3]
### Description

Hey Simon, cool project! In the README file you mention "Installation" and "Usage," yet legally no one can use this project in an app on the App Store because you hold the copyright. Could you put a LICENSE file in the repository to permit usage? I recommend the MIT open source license as it is the most popular in the Swift community and widely compatible. Thanks!

### Tasks

- [x] Make LICENSE file based on the MIT template

**Comment by simibac** [comment]
Thanks for the notification. Just added MIT licence. Let me know your app makes it to the app store so I can reference it.

**Comment by chrisjf** [comment]
Thank you!
