### ISSUE TITLE
make for UIKit, please :)

### ISSUE THREAD

**Issue by dimabiserov** [simibac/ConfettiSwiftUI#5]
| Priority        | Points           | Date           |
| :-------------: | :-------------:    | :-----:           |
| MEDIUM*          | x                   | YYYY-MM-DD |

\* LOW | MEDIUM | HIGH

### Story

As a ROLE, I want to ...GOAL, in order to ...BENEFIT

### Acceptance Criteria

- [ ] ...

------
### Implementation Tasks

- [ ] ...

**Comment by simibac** [comment]
I don't know UIKit very well. This was only a SwiftUI experiment for me to learn how to spwan animate and destroy views. Any PR addressing UIKit is appreciated.
