### ISSUE TITLE
Animation is over very fast

### ISSUE THREAD

**Issue by blockiyt** [simibac/ConfettiSwiftUI#6]
### Expected Behaviour
Describe the expected behaviour.
The popped out confetti should slowly rain down

### Actual Behaviour
Describe the actual behaviour.
The popped out confetti fastly rains down

### Steps to Reproduce the Issue
I am using this in combination with https://github.com/joogps/SlideOverCard. The library is the problem, because I tried it already on my Home Screen and there it worked fine. I would like to ask if you could tell me a solution :)

https://user-images.githubusercontent.com/65811753/135335692-14b5076c-ccf7-4460-9cb5-82d383bbb0d8.mov

**Comment by tobischw** [comment]
+1. Seeing same issue.

**Comment by claytonsulby** [comment]
+1. Agree

**Comment by simibac** [comment]
Thanks @claytonsulby for submitting a solution 🙏
