### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by kitlogan** [simibac/ConfettiSwiftUI#7]
### Expected Behaviour
App launch including package.

### Actual Behaviour
App crashed on launch with the console output attached.

### Steps to Reproduce the Issue
- Install Swift Package via Xcode package manager
- Build to iphone

![image](https://user-images.githubusercontent.com/61054641/139564273-4b3c2873-d480-466e-afdd-6c514ea86050.png)

**Comment by kitlogan** [comment]
Not sure how I'm installing it to my project incorrectly. Any advice/ help greatly appreciated! Thanks

**Comment by crorsavir54** [comment]
<img width="935" alt="Screen Shot 2021-11-03 at 11 51 22 AM" src="https://user-images.githubusercontent.com/9535612/140007808-694a4b78-e58c-43b8-8d0a-f7cb34fd538c.png">

I am also getting the same error

**Comment by simibac** [comment]
Were you able to resolve this issue?
