### ISSUE TITLE
Dynamic library prevents code signing from working in Xcode Cloud

### ISSUE THREAD

**Issue by joulupukki** [simibac/ConfettiSwiftUI#8]
In `Package.swift` this line forces you to choose either "Embed and Sign" or not to code sign when including ConfettiSwiftUI into an app (in Xcode):

```
type: .dynamic
```

This line isn't really needed.

I discovered this when attempting to build one of my apps with Xcode Cloud. Here's the error you get during the archive process:

```
ITMS-90334: Invalid Code Signature Identifier. The identifier "ConfettiSwiftUI-55554944d4fbc3d9c42f38d3b8bfbbc8cd81fa38" in your code signature for "ConfettiSwiftUI" must match its Bundle Identifier "ConfettiSwiftUI"
```

**Comment by simibac** [comment]
Thanks for the PR -> new release 0.3.0. Please close if it is resolved.

**Comment by joulupukki** [comment]
Awesome. Thanks for getting this in. My app now builds perfectly with Xcode Cloud.
